spring:
  application:
    name: open-social-api

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/open_social_db
    username: open_social_user
    password: open_social_password

  jpa:
    hibernate:
      ddl-auto: update  # or another setting, if preferred
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      encrypted:
  security:
    jwt:
      secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
      expiration-time: 3600000




springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /doc-ui

